#Hugo configuration
title = "32dsfd"
baseURL = "https:\/\/234sdaf.sdf.erewr"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
